class FilmPageLanguage {
  static String getLanguageName(String code) {
    switch (code) {
      case 'en':
        return 'English';
      case 'ru':
        return 'Russian';
      case 'jp':
        return 'Japanese';
      case 'fr':
        return 'French';
      case 'de':
        return 'German';
      case 'es':
        return 'Spanish';
      case 'zh':
        return 'Chinese';
      case 'it':
        return 'Italian';
      case 'ko':
        return 'Korean';
      case 'pt':
        return 'Portuguese';
      case 'ar':
        return 'Arabic';
      case 'hi':
        return 'Hindi';
      case 'tr':
        return 'Turkish';
      case 'pl':
        return 'Polish';
      case 'uk':
        return 'Ukrainian';
      case 'nl':
        return 'Dutch';
      case 'sv':
        return 'Swedish';
      case 'no':
        return 'Norwegian';
      case 'da':
        return 'Danish';
      case 'fi':
        return 'Finnish';
      case 'cs':
        return 'Czech';
      case 'hu':
        return 'Hungarian';
      case 'el':
        return 'Greek';
      case 'he':
        return 'Hebrew';
      case 'th':
        return 'Thai';
      case 'vi':
        return 'Vietnamese';
      case 'id':
        return 'Indonesian';
      case 'ms':
        return 'Malay';
      case 'ro':
        return 'Romanian';
      case 'bg':
        return 'Bulgarian';
      case 'hr':
        return 'Croatian';
      case 'sr':
        return 'Serbian';
      case 'sk':
        return 'Slovak';
      case 'lt':
        return 'Lithuanian';
      case 'lv':
        return 'Latvian';
      case 'et':
        return 'Estonian';
      case 'fa':
        return 'Persian';
      case 'ta':
        return 'Tamil';
      case 'te':
        return 'Telugu';
      case 'ml':
        return 'Malayalam';
      case 'kn':
        return 'Kannada';
      case 'mr':
        return 'Marathi';
      case 'bn':
        return 'Bengali';
      case 'pa':
        return 'Punjabi';
      case 'gu':
        return 'Gujarati';
      case 'ur':
        return 'Urdu';
      default:
        return 'Unknown';
    }
  }
}
